name: proxypin
description: ProxyPin
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.1+21

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  pointycastle: ^4.0.0
  logger: ^2.5.0
  date_format: ^2.0.9
  window_manager: ^0.4.3
  desktop_multi_window:
    git:
      url: https://gitee.com/wanghongenpin/flutter-plugins.git
      path: packages/desktop_multi_window
  path_provider: ^2.1.4
  file_picker: ^7.1.0+1
  proxy_manager: ^0.0.3
  easy_permission: ^1.0.0
  flutter_toastr: ^1.0.3
  share_plus: ^10.0.0
  flutter_js: ^0.8.1
  flutter_code_editor:
    git:
      url: https://github.com/wanghongenpin/flutter-code-editor.git
      ref: secure-keyboard
  flutter_desktop_context_menu: ^0.2.0
  device_info_plus: ^10.1.2
  shared_preferences: ^2.2.3
  image_pickers: 2.0.5+2
  url_launcher: ^6.3.1
  toastification: ^2.3.0

  qr_flutter: ^4.1.0
  flutter_qr_reader: ^1.0.5

  brotli: ^0.6.0

  macos_window_utils: ^1.8.3
  win32audio: ^1.3.1
  vclibs: ^0.1.3
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  url_launcher_linux: 3.1.1
# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/certs/ca.crt
    - assets/certs/ca_key.pem
    - assets/icon.png
    - assets/icon_foreground.png
    - assets/js/