/*
 * Copyright 2026 Hongen Wang All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import '../mcp_names.dart';

/// 局域网一键配置脚本生成：手机端 MCP 服务下发脚本，电脑端 `curl | sh`
/// （Windows 为 `irm | iex`）执行后，自动探测并配置已安装的 AI 客户端。
///
/// 覆盖：Claude Code（CLI，HTTP+Bearer）、Codex（~/.codex/config.toml 静态
/// http_headers）、Cursor 与 Gemini CLI（mcpServers JSON）。未安装的客户端跳过。
/// token 为十六进制随机串，endpoint 为 IP:port，注入脚本无注入风险。
///
/// @author wanghongen
class McpSetupScript {
  McpSetupScript._();

  static const _endpointPlaceholder = '__PROXYPIN_ENDPOINT__';
  static const _tokenPlaceholder = '__PROXYPIN_TOKEN__';
  static const _namePlaceholder = '__PROXYPIN_NAME__';
  static const _legacyPlaceholder = '__PROXYPIN_LEGACY__';

  static String _render(String template, {required String endpoint, required String token}) => template
      .replaceAll(_endpointPlaceholder, endpoint)
      .replaceAll(_tokenPlaceholder, token)
      .replaceAll(_namePlaceholder, McpClientNames.mobile)
      .replaceAll(_legacyPlaceholder, McpClientNames.legacy);

  static String shell({required String endpoint, required String token}) =>
      _render(_shellTemplate, endpoint: endpoint, token: token);

  static String powershell({required String endpoint, required String token}) =>
      _render(_psTemplate, endpoint: endpoint, token: token);

  // 脚本中 $ 变量需转义为 \$；占位符在运行时替换为实际 endpoint/token。
  static const String _shellTemplate = r'''
#!/bin/sh
# ProxyPin MCP one-click setup (generated by ProxyPin on your phone)
set -u
ENDPOINT="__PROXYPIN_ENDPOINT__"
TOKEN="__PROXYPIN_TOKEN__"
# Phone uses a distinct name so the desktop app's "proxypin" (stdio) entry is never overwritten.
NAME=__PROXYPIN_NAME__
ok=0

printf 'ProxyPin MCP setup -> %s\n\n' "$ENDPOINT"

# ---- Claude Code (CLI, user scope = global) ----
if command -v claude >/dev/null 2>&1; then
  # local scope is per-directory and shadows user scope; clear both before adding.
  # project scope (committed .mcp.json) is left untouched.
  claude mcp remove "$NAME" -s user >/dev/null 2>&1 || true
  claude mcp remove "$NAME" -s local >/dev/null 2>&1 || true
  # Remove legacy entry left in user scope by older app versions (never touch local: it belongs to desktop).
  claude mcp remove __PROXYPIN_LEGACY__ -s user >/dev/null 2>&1 || true
  if claude mcp add "$NAME" -s user --transport http "$ENDPOINT" --header "Authorization: Bearer $TOKEN" >/dev/null 2>&1; then
    printf '  [OK] Claude Code\n'; ok=1
  else
    printf '  [!!] Claude Code found but setup failed\n'
  fi
else
  printf '  [--] Claude Code not installed\n'
fi

# ---- Codex (~/.codex/config.toml, static http_headers) ----
if command -v codex >/dev/null 2>&1 || [ -d "$HOME/.codex" ]; then
  CODEX_DIR="$HOME/.codex"; mkdir -p "$CODEX_DIR"
  CODEX_TOML="$CODEX_DIR/config.toml"
  if [ -f "$CODEX_TOML" ]; then
    cp "$CODEX_TOML" "$CODEX_TOML.bak"
    awk -v name="$NAME" '
      $0 ~ "^\\[mcp_servers\\." name "(\\.http_headers)?\\]" { skip=1; next }
      skip && /^\[/ { skip=0 }
      !skip { print }
    ' "$CODEX_TOML" > "$CODEX_TOML.tmp" && mv "$CODEX_TOML.tmp" "$CODEX_TOML"
  fi
  cat >> "$CODEX_TOML" <<EOF

[mcp_servers.$NAME]
url = "$ENDPOINT"

[mcp_servers.$NAME.http_headers]
Authorization = "Bearer $TOKEN"
EOF
  printf '  [OK] Codex (~/.codex/config.toml)\n'; ok=1
else
  printf '  [--] Codex not installed\n'
fi

# ---- Cursor / Gemini CLI (mcpServers JSON, needs python3) ----
merge_json() {
  MCP_URL="$ENDPOINT" MCP_TOKEN="$TOKEN" MCP_NAME="$NAME" python3 - "$1" <<'PYEOF'
import json, os, sys
path = sys.argv[1]
url = os.environ["MCP_URL"]
token = os.environ["MCP_TOKEN"]
name = os.environ["MCP_NAME"]
parent = os.path.dirname(path)
if parent:
    os.makedirs(parent, exist_ok=True)
root = {}
if os.path.exists(path):
    try:
        with open(path, encoding="utf-8") as f:
            root = json.load(f) or {}
    except Exception:
        root = {}
if not isinstance(root, dict):
    root = {}
servers = root.setdefault("mcpServers", {})
if not isinstance(servers, dict):
    servers = {}
    root["mcpServers"] = servers
servers[name] = {
    "type": "http",
    "url": url,
    "headers": {"Authorization": "Bearer " + token},
}
with open(path, "w", encoding="utf-8") as f:
    json.dump(root, f, indent=2, ensure_ascii=False)
    f.write("\n")
PYEOF
}

if command -v python3 >/dev/null 2>&1; then
  if [ -d "$HOME/.cursor" ]; then
    CURSOR_JSON="$HOME/.cursor/mcp.json"
    [ -f "$CURSOR_JSON" ] && cp "$CURSOR_JSON" "$CURSOR_JSON.bak"
    if merge_json "$CURSOR_JSON"; then
      printf '  [OK] Cursor (~/.cursor/mcp.json)\n'; ok=1
    fi
  else
    printf '  [--] Cursor not installed\n'
  fi

  if [ -d "$HOME/.gemini" ]; then
    GEMINI_JSON="$HOME/.gemini/settings.json"
    [ -f "$GEMINI_JSON" ] && cp "$GEMINI_JSON" "$GEMINI_JSON.bak"
    if merge_json "$GEMINI_JSON"; then
      printf '  [OK] Gemini CLI (~/.gemini/settings.json)\n'; ok=1
    fi
  else
    printf '  [--] Gemini CLI not installed\n'
  fi
else
  printf '  [--] python3 not found, skipped Cursor / Gemini JSON config\n'
fi

printf '\n'
if [ "$ok" = "1" ]; then
  printf 'Done. Restart your AI client to load the ProxyPin MCP server.\n'
else
  printf 'No supported AI client detected. Configure manually with the JSON shown in the app.\n'
fi
''';

  static const String _psTemplate = r'''
# ProxyPin MCP one-click setup (generated by ProxyPin on your phone)
$ErrorActionPreference = 'Continue'
$Endpoint = '__PROXYPIN_ENDPOINT__'
$Token = '__PROXYPIN_TOKEN__'
# Phone uses a distinct name so the desktop app's "proxypin" (stdio) entry is never overwritten.
$Name = '__PROXYPIN_NAME__'
$script:ok = $false
# UTF-8 without BOM, so TOML/JSON parsers don't treat the BOM as an illegal character
$Utf8 = New-Object System.Text.UTF8Encoding($false)

Write-Host "ProxyPin MCP setup -> $Endpoint`n"

function Test-Cmd($n) { [bool](Get-Command $n -ErrorAction SilentlyContinue) }

# ---- Claude Code (CLI) ----
if (Test-Cmd claude) {
  # Native exe non-zero exit does not throw in PowerShell; check $LASTEXITCODE explicitly.
  # local scope is per-directory and shadows user scope; project scope (committed .mcp.json) untouched.
  claude mcp remove $Name -s user 2>$null | Out-Null
  claude mcp remove $Name -s local 2>$null | Out-Null
  # Remove legacy entry left in user scope by older app versions (never touch local: it belongs to desktop)
  claude mcp remove __PROXYPIN_LEGACY__ -s user 2>$null | Out-Null
  claude mcp add $Name -s user --transport http $Endpoint --header "Authorization: Bearer $Token" | Out-Null
  if ($LASTEXITCODE -eq 0) {
    Write-Host '  [OK] Claude Code'; $script:ok = $true
  } else {
    Write-Host "  [!!] Claude Code found but setup failed (exit $LASTEXITCODE)"
  }
} else {
  Write-Host '  [--] Claude Code not installed'
}

# ---- Codex (~/.codex/config.toml, static http_headers) ----
if ((Test-Cmd codex) -or (Test-Path (Join-Path $HOME '.codex'))) {
  $codexDir = Join-Path $HOME '.codex'
  New-Item -ItemType Directory -Force -Path $codexDir | Out-Null
  $codexToml = Join-Path $codexDir 'config.toml'
  if (Test-Path $codexToml) {
    Copy-Item $codexToml "$codexToml.bak" -Force
    # Drop the previous proxypin_mobile section: skip its header and body until the next section
    $out = New-Object System.Collections.Generic.List[string]
    $skip = $false
    foreach ($line in Get-Content $codexToml -Encoding UTF8) {
      if ($line -match "^\[mcp_servers\.$Name(\.http_headers)?\]") { $skip = $true; continue }
      if ($skip -and $line -match '^\[') { $skip = $false }
      if (-not $skip) { $out.Add($line) }
    }
    [System.IO.File]::WriteAllLines($codexToml, $out, $Utf8)
  }
  $block = @"

[mcp_servers.$Name]
url = "$Endpoint"

[mcp_servers.$Name.http_headers]
Authorization = "Bearer $Token"
"@
  [System.IO.File]::AppendAllText($codexToml, $block + "`n", $Utf8)
  Write-Host '  [OK] Codex (~/.codex/config.toml)'; $script:ok = $true
} else {
  Write-Host '  [--] Codex not installed'
}

# ---- Cursor / Gemini CLI (mcpServers JSON) ----
function Set-McpServerJson($path) {
  $dir = Split-Path $path
  if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
  if (Test-Path $path) { Copy-Item $path "$path.bak" -Force }
  $root = $null
  if (Test-Path $path) {
    try { $root = [System.IO.File]::ReadAllText($path, [System.Text.Encoding]::UTF8) | ConvertFrom-Json } catch { $root = $null }
  }
  if ($null -eq $root) { $root = [pscustomobject]@{} }
  $server = [pscustomobject]@{
    type = 'http'
    url = $Endpoint
    headers = [pscustomobject]@{ Authorization = "Bearer $Token" }
  }
  if ($null -eq $root.mcpServers) {
    $root | Add-Member -NotePropertyName mcpServers -NotePropertyValue ([pscustomobject]@{}) -Force
  }
  if ($null -ne $root.mcpServers.PSObject.Properties[$Name]) {
    $root.mcpServers.$Name = $server
  } else {
    $root.mcpServers | Add-Member -NotePropertyName $Name -NotePropertyValue $server
  }
  $json = $root | ConvertTo-Json -Depth 20
  [System.IO.File]::WriteAllText($path, $json + "`n", $Utf8)
}

$cursorDir = Join-Path $HOME '.cursor'
if (Test-Path $cursorDir) {
  try {
    Set-McpServerJson (Join-Path $cursorDir 'mcp.json')
    Write-Host '  [OK] Cursor (~/.cursor/mcp.json)'; $script:ok = $true
  } catch { Write-Host "  [!!] Cursor setup failed: $_" }
} else {
  Write-Host '  [--] Cursor not installed'
}

$geminiDir = Join-Path $HOME '.gemini'
if (Test-Path $geminiDir) {
  try {
    Set-McpServerJson (Join-Path $geminiDir 'settings.json')
    Write-Host '  [OK] Gemini CLI (~/.gemini/settings.json)'; $script:ok = $true
  } catch { Write-Host "  [!!] Gemini CLI setup failed: $_" }
} else {
  Write-Host '  [--] Gemini CLI not installed'
}

Write-Host ''
if ($script:ok) {
  Write-Host 'Done. Restart your AI client to load the ProxyPin MCP server.'
} else {
  Write-Host 'No supported AI client detected. Configure manually with the JSON shown in the app.'
}
''';
}
